### ISSUE TITLE
NPM audit reports MitM vulnerability on make-fetch-happen@4.0.2

### ISSUE THREAD

**Issue by alper-y** [silverwind/oui#12]
The error i'm getting is that: https-proxy-agent is the root cause.
The chain of its usage is: oui > make-fetch-happen > https-proxy-agent

`make-fetch-happen` has updated  its `https-proxy-agent` dependency to fix this security issue: https://github.com/npm/make-fetch-happen/commit/21416051f1f100cd7993af418f2e4da922d24a24

**Comment by silverwind** [comment]
Dependencies updated in https://github.com/silverwind/oui/commit/9be3d8d52109b6d7204080014fbf5208364845f1 and released as 10.0.30.
