### ISSUE TITLE
Missing Package Updates

### ISSUE THREAD

**Issue by ingvaldlorentzen** [silverwind/oui#13]
Hi, 

This package used to get weekly updates with data, but these seem to have stopped, with the last being April 4th. 

Is there an issue with the CI/CD pipeline maybe?

**Comment by silverwind** [comment]
Ah yes, I need to move these updates to the CI, they were previously done via a now defunct cron job.

**Comment by silverwind** [comment]
Fixed, 11.0.9 is available.
