### ISSUE TITLE
MAC Randomization

### ISSUE THREAD

**Issue by RWhite-EDR** [silverwind/oui#14]
It is my understanding that if the first octet ends in 2, 6, a, or e, then the MAC address has been randomized.  It is also my understanding that the entire MAC address is random, including the three OUI octets.

Is it possible to return some sort of indication that a MAC address is not being controlled by an OUI or manufacturer?

**Comment by silverwind** [comment]
> Is it possible to return some sort of indication that a MAC address is not being controlled by an OUI or manufacturer?

If it's not in the database, it is likely not officially registered with IEEE. But I would not take it as a 100% thing. Some manufactures are known to assign "fake" OUIs to extra interfaces in their devices and these will not look up correctly in the data, but still are technically "controlled".

This module is not meant to host special logic. It's just a wrapper around the official IEEE data, and I think I will convert the module to a simple JSON structure eventually.
