### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by LeoDog896** [silverwind/oui#15]
Using this module with any modern bundler (e.g. vite) breaks it.

**Comment by silverwind** [comment]
It's meant to be used in node only, but I could see transforming it to a JSON-only export, removing all dependencies.

**Comment by LeoDog896** [comment]
Maybe add a script to transform the JSON data into a js export? That way there can be both raw JSON data and a JSON export inside the module, then the NPM module can import from that js module.

**Comment by silverwind** [comment]
I think it's better to separate at least the CLI from the data, e.g. have two npm packages and then consumers of the data don't need to pull the CLI dependencies.

**Comment by parthiganesh** [comment]
> Using this module with any modern bundler (e.g. vite) breaks it.

Why don't you try, https://www.npmjs.com/package/mac-oui-lookup

**Comment by silverwind** [comment]
Module split is done, you can use https://github.com/silverwind/oui-data which is a pure JSON module with no dependencies.
