### ISSUE TITLE
update() method too slow.

### ISSUE THREAD

**Issue by roccomuso** [silverwind/oui#8]
The `update()` method is really but really slow.
That **oui.txt** file is not even provided from a CDN... and seems to be "streamed".

Perhaps is better to use wireshark's one?
`https://code.wireshark.org/review/gitweb?p=wireshark.git;a=blob_plain;f=manuf`

**Comment by silverwind** [comment]
Yes, the IEEE servers are probably heavily throttled, so it takes like 10 minutes to download. It is the most up-to-date source though. Maybe there's a mirror.

**Comment by silverwind** [comment]
http://linuxnet.ca/ieee/oui/ might be an option. I think I could just do automatic updates 1 day after they update.

**Comment by roccomuso** [comment]
Hmm, like this http://linuxnet.ca/ieee/oui/ ?

**Comment by silverwind** [comment]
Fixed in `5.0.0` which uses the new sanitized source file. If you still like to use the IEEE source, you can use [`options.url`](https://github.com/silverwind/oui#ouiupdateoptions-cb).

**Comment by roccomuso** [comment]
@silverwind Cool, really appreciated. I'll be using it in this my new project: [roccomuso/kickthemout](https://github.com/roccomuso/kickthemout)
